### ISSUE TITLE
선수 상세정보 차트 구현

### ISSUE THREAD

**Issue by gilmujjang** [gilmujjang/kotc_ranking#10]
승패 원형차트는 12시 방향을 시작점으로 수정,
순위는 원형차트가 아니라 상위 퍼센트를 숫자로 표현,
차트 데이터를 30개 이상으로 수정,
차트 오른쪽에 최근경기 표시

**Comment by paraang** [comment]
1. 원형 차트 시작 각도 수정
2. 원형 차트 전체적으로 수정 했는데 별로면 추후에 다시 수정 하겠습니다.
3. 차트 데이터 10-30-60으로 수정
4. 경기 기록 추가
