### ISSUE TITLE
유저 정보 중 start_rating의 데이터 타입

### ISSUE THREAD

**Issue by paraang** [gilmujjang/kotc_ranking#19]
'미영' 유저만 start_rating이 string으로 되어 있음.
사용자 생성 할 때 어떻게 입력하든 number 형태로 저장되도록 할 필요 있음.

**Comment by paraang** [comment]
다른 항목 들에 대해서도 마찬가지로 한 가지 데이터 타입으로만 저장되도록 수정 했으면 좋겠습니다.

**Comment by gilmujjang** [comment]
외부인 플레이어라 수동으로 입력하는 과정에서 실수가 있었네요 수정했습니다
외부인 플레이어도 등록할수있게 코드 수정하겠습니당

**Comment by paraang** [comment]
😄

**Comment by gilmujjang** [comment]
Done
