### ISSUE TITLE
멤버 리스트의 모달을 닫을 때 플레이어 경기 기록 초기화 문제

### ISSUE THREAD

**Issue by paraang** [gilmujjang/kotc_ranking#24]
멤버 리스트의 상세 정보 모달을 닫아도 게임 기록 렌더링 결과가 없어지고 남아있음.
확인 버튼을 눌렀을 때는 setPlayerGame([]) 으로 초기화 시킬 수 있지만
바깥을 눌렀을 때는 초기화가 안되서 그대로 남아있는 문제가 있음.

**Comment by gilmujjang** [comment]
해결완료
